name: Beta Release on Push to Main

on:
  push:
    branches:
      - clevel

jobs:
  package-beta-vsix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Get short commit SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Update version to beta.<run_number>
        run: |
          node -e "
            const fs = require('fs');
            const pkg = require('./package.json');
            const baseVersion = pkg.version.split('-')[0];
            const betaVersion = \`\${baseVersion}-beta.${{ github.run_number }}\`;
            pkg.version = betaVersion;
            fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
            console.log('Updated version:', betaVersion);
          "

      - name: Package VSIX
        run: npx vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-beta-${{ github.run_number }}
          path: "*.vsix"
