name: Branch-Based VSIX Release

on:
  push:
    branches:
      - "**"

jobs:
  release-vsix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Set version with branch suffix
        id: version
        run: |
          BRANCH="${GITHUB_REF##*/}"
          SAFE_BRANCH=$(echo "$BRANCH" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          BASE=$(node -p "require('./package.json').version.split('-')[0]")
          VERSION="${BASE}-${SAFE_BRANCH}.${GITHUB_RUN_NUMBER}"

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          node -e "
            const fs = require('fs');
            const pkg = require('./package.json');
            pkg.version = '$VERSION';
            fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
          "
          echo "Updated version to: $VERSION"

      - name: Package VSIX
        run: npx vsce package

      - name: Rename VSIX file
        run: |
          EXT_NAME=$(node -p "require('./package.json').name")
          mv *.vsix "$EXT_NAME-${{ steps.version.outputs.version }}.vsix"

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-${{ github.ref_name }}
          path: "*.vsix"
